on :
    push :
        branches :
            - master

jobs :
    
    build_android :
        runs-on : ubuntu-latest
        defaults : 
            run : 
                working-directory : android
        steps : 
            - uses: actions/checkout@v3
            
            - uses : actions/setup-java@v3
              with :
                distribution : zulu
                java-version: '11'
                
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.7.0

            - name : install deps
              run : npm i
              
            - name : ls
              run : ls
            
            - name : make_excutable
              run : chmod +x ./gradlew
            
            - name : build with graddle
              run :  ./gradlew assemble
